In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 12,4.8
#15, 6

In [52]:
dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m-%d %H:%M:%S')
data = pd.read_csv('C:/Users/C00310965/Documents/livros/source/dfsqs_analysis_20160923_30.csv',sep=';', parse_dates=['datetime'], index_col='datetime',date_parser=dateparse)
#data = pd.read_csv('C:/Users/C00310965/Documents/livros/source/dfsqs_analysis_20160923_30.csv',sep=';')
print data.head()
print '\n Data Types:'
print data.dtypes

                rnc  cellid  hsdpa_users  thp_hsdpa  latitude  longitude
datetime
2016-09-23  RNCDF04   61400        0.064     76.387  -15.8022   -47.8692
2016-09-23  RNCDF04   61401        0.156    658.168  -15.8022   -47.8692
2016-09-23  RNCDF04   61402        0.242    479.297  -15.8022   -47.8692
2016-09-23  RNCDF04   61403        0.069    131.217  -15.8022   -47.8692
2016-09-23  RNCDF04   61404        0.267    414.752  -15.8022   -47.8692

 Data Types:
rnc             object
cellid           int64
hsdpa_users    float64
thp_hsdpa      float64
latitude       float64
longitude      float64
dtype: object

In [58]:
#data.cellid.nunique()
#data.
dataslice = data[['cellid','latitude','longitude','hsdpa_users']]
#dataslice.dtypes

In [64]:
#dataslice.dtypes
#dataslice.index
dataslice.dropna()

            cellid  latitude  longitude  hsdpa_users
datetime
2016-09-23   61400  -15.8022   -47.8692        0.064
2016-09-23   61401  -15.8022   -47.8692        0.156
2016-09-23   61402  -15.8022   -47.8692        0.242
2016-09-23   61403  -15.8022   -47.8692        0.069
2016-09-23   61404  -15.8022   -47.8692        0.267
2016-09-23   61405  -15.8022   -47.8692        0.025
2016-09-23   61406  -15.8022   -47.8692        0.039
2016-09-23   61407  -15.8022   -47.8692        0.164
2016-09-23   61408  -15.8022   -47.8692        0.283
2016-09-23   61409  -15.8022   -47.8692        0.019
2016-09-23   61410  -15.8022   -47.8692        0.006
2016-09-23   61411  -15.8022   -47.8692        0.000
2016-09-23   61412  -15.7972   -47.8878        2.878
2016-09-23   61413  -15.7972   -47.8878        0.597
2016-09-23   61414  -15.7972   -47.8878        0.658
2016-09-23   61415  -15.7972   -47.8878        2.675
2016-09-23   61416  -15.7972   -47.8878        0.311
2016-09-23   61417  -15.7972   -47.8878        0.939
2016-09-23   61418  -15.7972   -47.8878        0.903
2016-09-23   61419  -15.7972   -47.8878        0.797
2016-09-23   61420  -15.7972   -47.8878        0.753
2016-09-23   61421  -15.7972   -47.8878        1.125
2016-09-23   61422  -15.7972   -47.8878        0.239
2016-09-23   61423  -15.7972   -47.8878        0.219
2016-09-23   61424  -15.8161   -47.8886        0.894
2016-09-23   61425  -15.8161   -47.8886        1.294
2016-09-23   61426  -15.8161   -47.8886        1.475
2016-09-23   61427  -15.8161   -47.8886        0.267
2016-09-23   61428  -15.8161   -47.8886        0.264
2016-09-23   61429  -15.8161   -47.8886        0.658
...            ...       ...        ...          ...
2016-09-30   63962  -15.7950   -47.8841        0.558
2016-09-30   63963  -15.7950   -47.8841        0.036
2016-09-30   63964  -15.7950   -47.8841        0.769
2016-09-30   63965  -15.7950   -47.8841        0.058
2016-09-30   63966  -15.7998   -47.8834        0.389
2016-09-30   63967  -15.7998   -47.8834        0.331
2016-09-30   64188  -15.7964   -47.8905        0.686
2016-09-30   64189  -15.7964   -47.8905        0.906
2016-09-30   64190  -15.7964   -47.8905        0.031
2016-09-30   64191  -15.7964   -47.8905        0.075
2016-09-30   64192  -15.7980   -47.9499        0.131
2016-09-30   64193  -15.7980   -47.9499        0.278
2016-09-30   64194  -15.8214   -47.9236        0.117
2016-09-30   64195  -15.8214   -47.9236        0.583
2016-09-30   64420  -15.7945   -47.8923        4.292
2016-09-30   64421  -15.7945   -47.8923        2.072
2016-09-30   64422  -15.7945   -47.8923        0.147
2016-09-30   64423  -15.7945   -47.8923        0.008
2016-09-30   64620  -15.8408   -47.9727        4.867
2016-09-30   64621  -15.8408   -47.9727        8.992
2016-09-30   64622  -15.8408   -47.9727        8.175
2016-09-30   64623  -15.8408   -47.9727        7.925
2016-09-30   64624  -15.8408   -47.9727        8.458
2016-09-30   64625  -15.8408   -47.9727        8.317
2016-09-30   64626  -15.8408   -47.9727        2.456
2016-09-30   64627  -15.8408   -47.9727        6.019
2016-09-30   64628  -15.8408   -47.9727        5.239
2016-09-30   64629  -15.8408   -47.9727        1.633
2016-09-30   64630  -15.8408   -47.9727        2.142
2016-09-30   64631  -15.8408   -47.9727        3.767

[479945 rows x 4 columns]

# Dynamic Time Warping

In [28]:
def DTWDistance(s1, s2):
    DTW={}

    for i in range(len(s1)):
        DTW[(i, -1)] = float('inf')
    for i in range(len(s2)):
        DTW[(-1, i)] = float('inf')
    DTW[(-1, -1)] = 0

    for i in range(len(s1)):
        for j in range(len(s2)):
            dist= (s1[i]-s2[j])**2
            DTW[(i, j)] = dist + min(DTW[(i-1, j)],DTW[(i, j-1)], DTW[(i-1, j-1)])

    return sqrt(DTW[len(s1)-1, len(s2)-1])

In [29]:
def euclid_dist(t1,t2):
    return sqrt(sum((t1-t2)**2))

In [30]:
##speeding up dtw
def DTWDistance(s1, s2,w):
    DTW={}

    w = max(w, abs(len(s1)-len(s2)))

    for i in range(-1,len(s1)):
        for j in range(-1,len(s2)):
            DTW[(i, j)] = float('inf')
    DTW[(-1, -1)] = 0

    for i in range(len(s1)):
        for j in range(max(0, i-w), min(len(s2), i+w)):
            dist= (s1[i]-s2[j])**2
            DTW[(i, j)] = dist + min(DTW[(i-1, j)],DTW[(i, j-1)], DTW[(i-1, j-1)])

    return sqrt(DTW[len(s1)-1, len(s2)-1])

In [48]:
import math
def LB_Keogh(s1,s2,r):
    LB_sum=0
    for ind,i in enumerate(s1):

        lower_bound=min(s2[(ind-r if ind-r>=0 else 0):(ind+r)])
        upper_bound=max(s2[(ind-r if ind-r>=0 else 0):(ind+r)])

        if i>upper_bound:
            LB_sum=LB_sum+(i-upper_bound)**2
        elif i<lower_bound:
            LB_sum=LB_sum+(i-lower_bound)**2

    return math.sqrt(LB_sum)

# K-Means

In [49]:
import random

def k_means_clust(data,num_clust,num_iter,w=5):
    centroids=random.sample(data,num_clust)
    counter=0
    for n in range(num_iter):
        counter+=1
        print counter
        assignments={}
        #assign data points to clusters
        for ind,i in enumerate(data):
            min_dist=float('inf')
            closest_clust=None
            for c_ind,j in enumerate(centroids):
                if LB_Keogh(i,j,5)<min_dist:
                    cur_dist=DTWDistance(i,j,w)
                    if cur_dist<min_dist:
                        min_dist=cur_dist
                        closest_clust=c_ind
            if closest_clust in assignments:
                assignments[closest_clust].append(ind)
            else:
                assignments[closest_clust]=[]

        #recalculate centroids of clusters
        for key in assignments:
            clust_sum=0
            for k in assignments[key]:
                clust_sum=clust_sum+data[k]
            centroids[key]=[m/len(assignments[key]) for m in clust_sum]

    return centroids

In [50]:
from sklearn.cross_validation import train_test_split
df = data
train, test = train_test_split(df, test_size = 0.2)
#train = np.genfromtxt('C:/Users/C00310965/Documents/livros/source/DFSQS_traffic_lte.csv',delimiter=';')
#test = np.genfromtxt('datasets/test.csv', delimiter='\t')

#dt=np.vstack((train[:,:-1],test[:,:-1]))
dt=np.vstack((train,test))
#data=np.vstack((train[:,:-1]))

import matplotlib.pylab as plt

centroids=k_means_clust(dt,4,10,4)
for i in centroids:

    plt.plot(i)

plt.show()

1

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [65]:
from sklearn.cross_validation import train_test_split
df = dataslice
train, test = train_test_split(df, test_size = 0.2)
#train = np.genfromtxt('C:/Users/C00310965/Documents/livros/source/DFSQS_traffic_lte.csv',delimiter=';')
#test = np.genfromtxt('datasets/test.csv', delimiter='\t')

In [ ]:
##preprocessing
#train.isnull().values.any()
train_new = train.dropna(how='any') 
#dataslice
nan_rows = train_new[train_new.isnull().T.any().T]
nan_rows

In [ ]:
#dt=np.vstack((train,test))
import numpy as np
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(train_new)
labels = kmeans_model.labels_
metrics.silhouette_score(train_new, labels, metric='euclidean')